name: retain_json_test

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # install the python version needed
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
    - name: execute py script # run add_run_details.py to get the latest data
      run: python add_run_details.py    
    - name: commit files
      env:
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      run: |
        git config --local user.email "kaustubhgoyal118@gmail.com"
        git config --local user.name "Kaustubh0699"
        git remote set-url origin "https://$TOKEN_GITHUB@github.com/Kaustubh0699/MLOps_WineQuality.git"
        git add runs.json
        git commit -m "update runs.json" -a
        git push      
    # - name: push changes
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     github_token: ${{ secrets.TOKEN_GITHUB }}
    #     force: true  